version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

# TODO добавить сервисы
  rating:
    build: ./v4/rating
    container_name: rating_service
    restart: on-failure
    environment:
      DATABASE_URL: postgresql://program:test@postgres:5432/ratings
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "8050:8050"
    depends_on:
      - postgres

  library:
    build: ./v4/rating  # путь к папке с Library, поправь на свой
    container_name: library_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://program:test@postgres:5432/libraries
    ports:
      - "8060:8060"

volumes:
  db-data: